EXTAUTH_AUTH_URL = None

EXTAUTH_APP_NAME = None

EXTAUTH_AUTH_TIMEOUT = 5

EXTAUTH_SESSIONID_COOKIE_NAME = 'sessionid'

EXTAUTH_CREATE_PROFILE_ON_ACCESS = True

EXTAUTH_CREATE_USER_ON_ACCESS = False

EXTAUTH_USERNAME_FIELD = 'username'

EXTAUTH_USER_EXTRA_FIELDS = (
    ('username', 'username'),
    ('email', 'email')
)
/